Doc optimize control info
DassHydro/smash pull request #109
Opened 2023-12-05 16:29 UTC by inoelloc

Add docstring to control information methods and quick fix on control deallocation

2023-12-06 23:18 UTC, nghi-truyen requested changes
J'ai juste quelques remarques mineures.

2023-12-06 23:18 UTC, nghi-truyen commented on smash/core/simulation/_doc.py
> +Information on the optimisation control vector of Model.
Je crois qu'on écrit plutôt "optimization" dans la plupart de la doc (tu peux rechecker poiur vérifier)

2023-12-06 23:18 UTC, nghi-truyen commented on smash/core/simulation/_doc.py
> +        A dictionary containing the type of prior to link to control vector. The keys are any control parameter name (i.e. ``'cp0'``, ``'cp1-1'``, ``'cp-slope-a'``, etc),
Peut-être mettre un . après etc:
(i.e. ``'cp0'``, ``'cp1-1'``, ``'cp-slope-a'``, etc.)

2023-12-06 23:18 UTC, nghi-truyen commented on smash/core/simulation/_doc.py
> +This gives a direct indication of what the optimizer takes as input, depending on the optimisation configuration set up.
Pareil pour "optimization" pour la cohérence

2023-12-06 23:18 UTC, nghi-truyen commented on smash/core/simulation/_doc.py
> +the optimisation options. This is why we can define all the optimisation options in the
Pareil "optimization"

2023-12-07 16:01 UTC, inoelloc commented
> J'ai juste quelques remarques mineures.

Ca devrait etre bon !

2023-12-07 16:16 UTC, merged