Exponential store gr6
DassHydro/smash pull request #210
Opened 2024-06-12 09:36 UTC by asjeb

Exponential reservoir inspired by airGR : https://hydrogr.github.io/airGR/

2024-06-14 10:41 UTC, inoelloc reviewed
Voilà à toi. Je n'ai pas mis de commentaire sur toutes les modifications si ca se répétait.

2024-06-14 10:41 UTC, inoelloc commented on doc/source/user_guide/index.rst
> +    others/gr6.rst
```suggestion
    others/cance_gr6.rst
```
Pour être homogène avec les autres guides ?

Je pense que la description des conventions des données d'entrée devrait aller entre le Quick Start et le Classical uses. On peut laisser dans Others le tuto sur gr6 avec tous les autres tutos qui iraient pas dans Classical Uses. @pag13 Tu en penses quoi ?

2024-06-14 10:41 UTC, inoelloc commented on doc/source/user_guide/others/gr6.rst
> +with :math:`c_e` the characteristic time of the water level recession and the level is :math:`h_e` (:math:`mm`).
La tu as ecrit le temps caractéristique de récession. Si c'est bien ca, je nommerais autrement le paramètre pour pas confondre avec une capacité. ``le`` peut etre, j'en sais rien :3

2024-06-14 10:41 UTC, inoelloc commented on doc/source/math_num_documentation/forward_structure.rst
> +    l_{exc}(x, t) = k_{exc}(x) \left(h_t(x, t - 1) - a_{exc}(x)\right)
Mettre ``same as gr5 exchange`` ?

2024-06-14 10:41 UTC, inoelloc commented on doc/source/math_num_documentation/forward_structure.rst
> +- Split the production runoff :math:`p_r` into three branches (transfer, exponential and direct), :math:`p_{rr}` and :math:`p_{rd}`
```suggestion
- Split the production runoff :math:`p_r` into three branches (transfer, exponential and direct), :math:`p_{rr}`, :math:`p_{re}` and :math:`p_{rd}`
```

2024-06-14 10:41 UTC, inoelloc commented on doc/source/math_num_documentation/forward_structure.rst
> +- Compute the exponential branch elemental discharge :math:`q_{re}`
```suggestion
- Compute the exponential branch elemental discharge :math:`q_e`
```
q_e pour etre homogene avec q_d et q_r ?

2024-06-14 10:41 UTC, inoelloc commented on doc/source/user_guide/others/gr6.rst
> +In the GR6 module from airGR package https://hydrogr.github.io/airGR, they suggest some treatments of the asymptotic behaviors of the quantity :math:`q_{re}`, as follow :
Ca vient du papier les traitements, apres airGR applique des traitements différents mais je citerais plutot le papier

2024-06-14 10:41 UTC, inoelloc commented on doc/source/user_guide/others/gr6.rst
> +        STOP: TOTAL NO. OF ITERATION EXCEEDS LIMIT
Dans l'idée, c'est pratique, ca évite de relancer les calculs à chaque modification du fichier mais dès que tu vas modifier du code, il faudra mettre à jour le texte aussi. C'est vrai que c'est vite pénible de faire de la documentation avec des optimisations ...

2024-06-14 10:41 UTC, inoelloc commented on doc/source/user_guide/others/gr6.rst
> +We can show NSE and KGE errors on the distributed solution.
La c'est les résultats du forward run non ?

2024-06-14 10:41 UTC, inoelloc commented on doc/source/user_guide/others/gr6.rst
> +    f.colorbar(map_aexc, ax=ax[1,1], label="aexc (mm/d)");
```suggestion
    f.colorbar(map_aexc, ax=ax[1,1], label="aexc (mm/d)");
```
aexc doit etre sans unité il me semble

2024-07-09 12:51 UTC, pag13 commented on doc/source/math_num_documentation/forward_structure.rst
> +:math:`c_e` the maximum capacity of the exponential reservoir,
Corriger pour le réservoir exponentiel

2024-07-09 12:51 UTC, pag13 commented on doc/source/user_guide/index.rst
> +    others/gr6.rst
Oui, conventions et unités des data et grandeurs, au plus tôt donc quickstart oui, ainsi que classical uses + peut etre une section dediee qqpart sur notations, units, ... ?

2024-07-09 12:51 UTC, pag13 commented on doc/source/user_guide/others/gr6.rst
> +with :math:`c_e` the characteristic time of the water level recession and the level is :math:`h_e` (:math:`mm`).
je suis d'accord avec FC

2024-07-09 12:51 UTC, pag13 commented on doc/source/user_guide/others/gr6.rst
> +In the GR6 module from airGR package https://hydrogr.github.io/airGR, they suggest some treatments of the asymptotic behaviors of the quantity :math:`q_{re}`, as follow :
oui citer l'article

2024-07-09 12:51 UTC, pag13 commented on doc/source/user_guide/others/gr6.rst
> +We can show NSE and KGE errors on the distributed solution.
le préciser ds le titre du plot plus explicitement "forward run"

2024-07-09 12:51 UTC, pag13 commented on smash/fcore/operator/md_gr_operator.f90
> +    subroutine exponential_transfer(he, pre, ce, qre)
absolument

2024-07-09 12:51 UTC, pag13 commented on smash/fcore/operator/md_gr_operator.f90
> +                ac_qt(k) = qr + qd
oui

2024-07-22 07:34 UTC, asjeb commented on doc/source/user_guide/others/gr6.rst
> +with :math:`c_e` the characteristic time of the water level recession and the level is :math:`h_e` (:math:`mm`).
c_e renommé t_e

2024-07-22 14:30 UTC, nghi-truyen commented on smash/fcore/operator/md_gr_operator.f90
> +            qre = te * log(exp(AR) + 1._sp)
```suggestion
        real(sp) :: he_star, ar
        
        he_star = he + pre
        ar = he_star / te
        if (ar .lt. -7._sp) then
            qre = te * exp(ar)
        else if (ar .gt. 7._sp) then
            qre = he_star + te / exp(ar)
        else
            qre = te * log(exp(ar) + 1._sp)
```
On utilise souvent les caratères majuscules pour le nom  des types dérivés en Fortran ou des classes en Python.

2024-07-22 14:30 UTC, nghi-truyen commented on smash/tests/test_constant.py
> +        ["ci", "cp", "ct", "ce", "kexc", "aexc"],  # % gr5
```suggestion
        ["ci", "cp", "ct", "ce", "kexc", "aexc"],  # % gr6
```
gr6?

2024-07-22 14:45 UTC, nghi-truyen reviewed
Faudrait rajouter aussi "gr6" dans le docstring de Model -> setup -> hydrological_module dans le fichier model.py.

2024-07-22 14:46 UTC, nghi-truyen requested changes
Faudrait rajouter aussi "gr6" dans le docstring de Model -> setup -> hydrological_module dans le fichier model.py.

2024-07-23 07:33 UTC, asjeb commented on doc/source/user_guide/others/gr6.rst
> +In the GR6 module from airGR package https://hydrogr.github.io/airGR, they suggest some treatments of the asymptotic behaviors of the quantity :math:`q_{re}`, as follow :
AirGR n'applique pas ce qu'il y a dans le papier

2024-07-23 07:43 UTC, asjeb commented on doc/source/user_guide/others/gr6.rst
> +In the GR6 module from airGR package https://hydrogr.github.io/airGR, they suggest some treatments of the asymptotic behaviors of the quantity :math:`q_{re}`, as follow :
Je fais des sciences reproductibles, je vais mettre les deux.

2024-07-23 10:04 UTC, asjeb commented
Personnellement, je trouve que ce GR6, ne se comporte pas bien numériquement. 
La version que j'avais écrite en janvier donnait des résultats bien meilleurs. L'interprétation n'était pas fausse car dans pushpalatha, le 6e paramètre s'exprime en mm, alors que dans Michel le 6e paramètre s'exprime en temps : quid des unites dans airGR Qre en mm, puis St(3) en mm/s ?

2024-07-23 10:06 UTC, asjeb commented
A voir sur un cas plus complexe que la Cance je pense.

2024-07-23 11:26 UTC, inoelloc commented
> Personnellement, je trouve que ce GR6, ne se comporte pas bien numériquement. La version que j'avais écrite en janvier donnait des résultats bien meilleurs. L'interprétation n'était pas fausse car dans pushpalatha, le 6e paramètre s'exprime en mm, alors que dans Michel le 6e paramètre s'exprime en temps : quid des unites dans airGR Qre en mm, puis St(3) en mm/s ?

@asjeb
Ca veut dire quoi "se comporte pas bien numériquement" ? Les résultats sur le cas test Cance ne sont pas suffisants pour juger de la performance d'une structure. Il faudrait au moins prendre plusieurs années de calage, plusieurs bassins et faire de la validation temporelle. Les performances de calage en soit, c'est pas le plus important. Le cas test Cance te permet juste de vérifier que ton code fonctionne et que le résultat ressemble à un comportement hydrologique.
Pour moi, dans michel, le paramètre s'exprime aussi en mm. Il n'y a que dans les commentaires de airGR qu'ils parlent de temps pour ce paramètre: `! Param(6) : time constant of exponential store (X6 - EXP) [day]` et St est bien en mm: `! [numeric] exponential store level (St(3)) (negative) [mm]`. Je pense que c'est airGR qui se trompe sur l'unité du paramètre du réservoir exponentiel et que c'est bien des mm comme dans pushpalatha et michel.

2024-07-23 12:12 UTC, asjeb commented
St(3)=St(3)-QRExp 

! QRExp  ! [numeric] outflow from exponential store (QRExp) [mm/day]
! Exp    ! [numeric] exponential store level (St(3)) (negative) [mm]

2024-07-23 12:16 UTC, asjeb commented
Par ailleurs j'ai renommé le ce en te...

2024-07-23 12:23 UTC, inoelloc commented
> St(3)=St(3)-QRExp
> 
> ! QRExp ! [numeric] outflow from exponential store (QRExp) [mm/day] ! Exp ! [numeric] exponential store level (St(3)) (negative) [mm]

Oui voila meme eux sont pas cohérents dans leur notation. Pour moi QRExp c'est des mm aussi. Juste des mm pour chaque pas de temps de simulation donc en journalier, des mm/day si on veut

2024-07-23 12:25 UTC, inoelloc commented
> Par ailleurs j'ai renommé le ce en te...

Au pire, pas grave ca. On peut dire que c'est `te` pour `trucmuche exponentiel` :3

2024-07-23 12:29 UTC, asjeb commented
Yes tout est en mm. C'est le plus logique avec leur notation.

2024-07-24 10:38 UTC, asjeb commented
Je pense être arrivée difficilement au bout de cette PR. 
Il y a un meilleur nom à trouver pour le paramètre de décrue que j'ai renommé te. le ne me convient pas trop car cela me fait penser au lexc...

2024-07-24 12:24 UTC, nghi-truyen commented on doc/source/user_guide/others/cance_gr6.rst
> +.. _user_guide.others.gr6:
À mon avis, je ne mettrais pas un user guide sur GR6 car :
- En termes d'utilisation, il n'y a aucune différence entre GR6 et les autres structures. Donc, je ne pense pas que ce soit pertinent de l'ajouter ici.
- La comparaison des modèles ne rentre absolument pas dans un user guide, ce n'est pas le but. De plus, même si tu veux faire une étude de cas pour conclure quelque chose, ce ne serait pas sur un cas test sur la Cance avec seulement deux événements de crues.

2024-07-24 13:06 UTC, asjeb commented on doc/source/user_guide/index.rst
> +    others/cance_gr6.rst
Oui je suis d'accord, On m'avait demandé d'écrire ce que j'avais compris du model GR6, je l'ai mis dans others pour donner des explications, peut-être faudrait-il le mettre autre part ?

2024-07-24 13:18 UTC, nghi-truyen approved these changes

2024-07-24 13:40 UTC, nghi-truyen requested changes
C'est bon pour moi et je laisse François approuver si c'est ok pour lui

2024-07-24 13:53 UTC, inoelloc commented on doc/source/math_num_documentation/forward_structure.rst
Je sais pas ce qui s'est passé dans ce fichier mais il y a du avoir un souci dans un merge de main vers cette branche. On est sur une ancienne version de ce fichier, sans les tableaux déroulants pour les structures (enfin que pour gr4)

2024-07-24 13:53 UTC, inoelloc commented on doc/source/math_num_documentation/forward_structure.rst
J'ai aussi le schéma en svg pour gr6 que je peux te filer !

2024-07-24 13:53 UTC, inoelloc commented on smash/_constant.py
> +            ["pn", "en", "pr", "perc", "lexc", "prr", "prd", "pre", "qr", "qd", "qre", "qt"],  # % gr6
```suggestion
            ["pn", "en", "pr", "perc", "lexc", "prr", "prd", "pre", "qr", "qd", "qe", "qt"],  # % gr6
```

2024-07-24 13:53 UTC, inoelloc commented on smash/_constant.py
> +            (0, 100),  # % te
Pourquoi 100 ?

2024-07-24 13:53 UTC, inoelloc commented on smash/_constant.py
> +            (-np.inf, 1),  # % he
Pourquoi 1 ?

2024-07-24 13:53 UTC, inoelloc commented on smash/tests/diff_baseline.csv
Y a du avoir aussi un souci avec un merge dans de fichier

2024-07-24 13:53 UTC, inoelloc commented on smash/tests/test_constant.py
> +        ["pn", "en", "pr", "perc", "lexc", "prr", "prd", "pre", "qr", "qd", "qre", "qt"],  # % gr6
```suggestion
        ["pn", "en", "pr", "perc", "lexc", "prr", "prd", "pre", "qr", "qd", "qe", "qt"],  # % gr6
```

2024-07-24 13:53 UTC, inoelloc commented on smash/tests/diff_baseline.csv
On revient encore sur l'histoire que le setup de test est à revoir ... Est ce que tu peux repartir de la baseline de main actuelle et relancer le make test-baseline stp :/

2024-07-24 14:12 UTC, asjeb commented on smash/_constant.py
> +            (0, 100),  # % te
Dans Pushpalatha, ce param est entre 0 et 20 si mes souvenir sont bons, j'ai pris une gamme plus large, mais on peut réduire.

2024-07-24 14:35 UTC, asjeb commented on smash/_constant.py
> +            (-np.inf, 1),  # % he
Dans airGR, ils spécifient que ce param est négatif, d'ailleurs s'il ne l'était pas le gradient partirait loin. J'ai mis 1 pour aller cherche un peu plus loin dans un descente de gradient.

2024-07-24 14:36 UTC, asjeb commented on smash/tests/diff_baseline.csv
De mm pour la documentation ?

2024-07-24 14:36 UTC, asjeb commented on smash/tests/test_constant.py
> +        ["pn", "en", "pr", "perc", "lexc", "prr", "prd", "pre", "qr", "qd", "qre", "qt"],  # % gr6
Je pourrais jurer avoir mis qe au lieu de qre.

2024-07-24 14:38 UTC, asjeb commented on doc/source/math_num_documentation/forward_structure.rst
Je veux bien le svg. Tu utilises quoi comme outil pour le générer ?

2024-07-24 14:44 UTC, inoelloc commented on smash/_constant.py
> +            (-np.inf, 1),  # % he
Cet état est défini sur ``]-inf, +inf[`` ?

2024-07-24 14:53 UTC, inoelloc commented on doc/source/math_num_documentation/forward_structure.rst
![gr6_structure](https://github.com/user-attachments/assets/c368b04d-6aa7-4f43-8253-a088a9862c8a)
Je fais sur Inkscape. Je viens de voir que j'avais utilisé ``be`` pour le nom du paramètre du reservoir. Je pense qu'il y a que ca à modifier sur le fond.

2024-07-24 14:54 UTC, inoelloc commented on smash/tests/diff_baseline.csv
j'imagine oui

2024-07-25 13:28 UTC, asjeb commented
Changement de nom t_e -> b_e fait.

2024-07-26 07:22 UTC, inoelloc approved these changes
Au dernier détail pres, tout bon pour moi ! Merci !

2024-07-26 07:22 UTC, inoelloc commented on doc/source/math_num_documentation/forward_structure.rst
> +    :math:`t_e` controls the slope of the recession,
```suggestion
    :math:`b_e` controls the slope of the recession, 
```

2024-07-26 08:32 UTC, asjeb commented
Ah oui j'en avais oublié un ! Il y a un T_e dans la présentation du module de neige, donc j'ai préféré le faire à la main dans la doc.
Merci à vous deux

2024-07-26 08:41 UTC, nghi-truyen approved these changes

2024-07-26 08:42 UTC, merged