Model variant grc reunion
DassHydro/smash pull request #305
Opened 2024-09-05 14:10 UTC by maximejay

Voici une nouvelle variante de modélisation spéciale Réunion : Grc
-> rebaser sur main le 04/09/2024 (le merge devrait être facile)
-> j'ai ajouté la doc + un schéma
-> un nouveau paramètre en plus pour le second réservoir de transfert: cl
-> make tap

Pb rencontrés:
-> la doc de compile pas à cause du pb suivant qui m'échappe (j'ai pas touché à ces fichiers)
/smash/doc/source/api_reference/sub-packages/factory.rst:32:la table des matières contient des références à des documents inexistants 'api_reference/sub-packages/smash/smash.factory.Net.add_dense' [toc.not_readable]
An error occurred while generating the documentation. Returning to previous version.

Merci :)

2024-09-07 11:08 UTC, pag13 requested changes
Salut, 
Une bonne chose d'avoir ajouté la structure du modèle opérationnel actuel sur la Réunion. 
Upgrader le diagramme du modèle dans le mm style que les autres modèles - cf. pptx propre crée avant l'été et déposé sur le git ;)
Merci,
PAG

2024-09-07 11:08 UTC, pag13 commented on doc/source/_static/grc_structure.png
Ok to include this more parameterized structure this way from previous version. 

Not the right style of diagram upgrade accordingly please (cf. pptx file provided in the git)

2024-09-07 11:08 UTC, pag13 commented on doc/source/math_num_documentation/forward_structure.rst
> +    :math:`h_l` the state of the slow transfer reservoir.
h_t and h_l not in agreement with notation on diagram (update diagram since this is h_t l in code below)

2024-09-10 13:54 UTC, inoelloc commented
Closed and replaced by #313

2024-09-10 13:54 UTC, closed without merging