GR with imperviousness
DassHydro/smash pull request #349
Opened 2024-11-20 15:00 UTC by asjeb

GR structures with imperviousness coefficient on neutralised rain pn tested by Ahmad, in particular for cases of intense rainfall

2024-11-20 15:15 UTC, asjeb commented
J'ai considéré que Pn était modifiée par le coeff d'imper.

2024-11-30 05:24 UTC, pag13 approved these changes
Merci Apolline pour cette fusion de "imperviousness" et "rain_intensity", ça m'a l'air ok.
Un tuto sur l'usage de imperviousness me parait nécessaire, aussi rain intensity => à discuter pour v1.1.
Je n'ai pas regardé la doc et ferai un passage complet pour v1.1, de vérifications et compléments.

2024-11-30 05:24 UTC, pag13 commented on smash/_constant.py
>              (-50, 50),  # % kexc
Pour alpha 1, 2, est ce les bornes testées par Ahmad sur jeu 235BV FR ?

2024-11-30 05:24 UTC, pag13 commented on smash/core/model/_read_input_data.py
> +        )
ok useful error message

2024-11-30 05:24 UTC, pag13 commented on smash/core/model/_standardize.py
> +
ok

2024-11-30 05:24 UTC, pag13 commented on smash/fcore/operator/md_gr_operator.f90
> +
Ainsi, la version que l'on a discuté considerant  en ou en-ei comme ""potentiel d'etp"" et que pas d'evapo sur les surf impermeables, à expliciter a minima dans doc svp.

2024-12-11 14:11 UTC, nghi-truyen requested changes
Voilà ma review, j'ai eu pas mal de commentaires sur la déclaration des varaibles Fortran et notamment la déclaration de "imperviousness" pour l'OMP, ça doit être déclaré et toujours dans "private" variables. Je sais pas comment il marche quand tu le déclare comme "shared" variables mais je pense que ça doit être corrigé pour que l'OMP fonctionne correctement dans smash.

2024-12-11 14:11 UTC, nghi-truyen commented on smash/fcore/operator/md_gr_operator.f90
>          real(sp) :: beta, pr, perc, ps, es, l, prr, pre, prd, qr, qd, qe
```suggestion
        real(sp) :: beta, imperviousness, pr, perc, ps, es, l, prr, pre, prd, qr, qd, qe
```

2024-12-11 14:11 UTC, nghi-truyen commented on smash/fcore/operator/md_gr_operator.f90
> +        real(sp) :: imperviousness
```suggestion
```

2024-12-11 14:11 UTC, nghi-truyen commented on smash/fcore/operator/md_gr_operator.f90
> +                imperviousness = input_data%physio_data%imperviousness(row, col)
Pareil, il faut déclarer dans "private"

2024-12-11 14:11 UTC, nghi-truyen commented on smash/fcore/operator/md_gr_operator.f90
>          real(sp) :: pn, en, pr, perc, ps, es, l, prr, prl, prd, qr, ql, qd
```suggestion
        real(sp) :: pn, en, imperviousness, pr, perc, ps, es, l, prr, prl, prd, qr, ql, qd
```

2024-12-11 14:11 UTC, nghi-truyen commented on smash/fcore/operator/md_gr_operator.f90
> +        real(sp) :: imperviousness
```suggestion
```

2024-12-11 14:11 UTC, nghi-truyen commented on smash/fcore/operator/md_gr_operator.f90
>          real(sp) :: pr, perc, ps, es, l, prr, prl, prd, qr, ql, qd
```suggestion
        real(sp) :: imperviousness, pr, perc, ps, es, l, prr, prl, prd, qr, ql, qd
```

2024-12-11 14:11 UTC, nghi-truyen commented on smash/fcore/operator/md_gr_operator.f90
> +        real(sp) :: imperviousness
```suggestion
```

2024-12-11 14:11 UTC, nghi-truyen commented on smash/fcore/operator/md_gr_operator.f90
>          !$OMP& private(row, col, k, time_step_returns, pr, perc, ps, es, l, prr, prl, prd, qr, ql, qd)
Dans "private" :
```suggestion
        !$OMP& ac_cp, ac_ct, ac_cl, ac_kexc, ac_hp, ac_ht, ac_hl, ac_qt, pn, en) &
        !$OMP& private(row, col, k, time_step_returns, imperviousness, pr, perc, ps, es, l, prr, prl, prd, qr, ql, qd)
```

2024-12-11 14:11 UTC, nghi-truyen commented on smash/fcore/operator/md_gr_operator.f90
>          real(sp) :: ei, pn, en, pr, perc, ps, es, prr, qr
```suggestion
        real(sp) :: ei, pn, en, imperviousness, pr, perc, ps, es, prr, qr
```

2024-12-11 14:11 UTC, nghi-truyen commented on smash/fcore/operator/md_gr_operator.f90
> +        real(sp) :: imperviousness
```suggestion
```

2024-12-11 14:11 UTC, nghi-truyen commented on smash/fcore/operator/md_gr_operator.f90
>          real(sp) :: pr, perc, ps, es, prr, qr
```suggestion
        real(sp) :: imperviousness, pr, perc, ps, es, prr, qr
```

2024-12-11 14:11 UTC, nghi-truyen commented on smash/fcore/operator/md_gr_operator.f90
> +        real(sp) :: imperviousness
```suggestion
```

2024-12-11 14:11 UTC, nghi-truyen commented on smash/fcore/operator/md_gr_operator.f90
>          !$OMP& private(row, col, k, time_step_returns, pr, perc, ps, es, prr, qr)
Dans private :
```suggestion
        !$OMP& ac_cp, ac_ct, ac_hp, ac_ht, ac_qt, ei, pn, en) &
        !$OMP& private(row, col, k, time_step_returns, imperviousness, pr, perc, ps, es, prr, qr)
```

2024-12-11 14:11 UTC, nghi-truyen commented on smash/fcore/operator/md_gr_operator.f90
>          !$OMP& private(row, col, k, time_step_returns, pr, perc, ps, es, prr, prd, qr, qd)
```suggestion
        !$OMP& ac_ca, beta, ac_cc, ac_kb, ac_ha, ac_hc, ac_qt, ei, pn, en) &
        !$OMP& private(row, col, k, time_step_returns, imperviousness, pr, perc, ps, es, prr, prd, qr, qd)
```

2024-12-13 10:08 UTC, nghi-truyen approved these changes

2024-12-13 10:12 UTC, merged